<a href="https://colab.research.google.com/github/shila121/datasets/blob/main/ann_s.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing libraries

import numpy as np
import pandas as pd
import tensorflow as tf


In [2]:
tf.__version__

'2.3.0'

In [3]:
# Part 1:Data preprocessing

# importing the dataset
dataset = pd.read_excel('Folds5x2_pp.xlsx')

dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [4]:
# splitting the data into features and target
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [5]:
# splitting the dataset into training and test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [6]:
# Part 2:Building ANN

# initalistion of ann
ann = tf.keras.models.Sequential()

# adding input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units = 6,activation ='relu'))

# adding second hidden layer
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))

# adding output layer
ann.add(tf.keras.layers.Dense(units = 1))

In [7]:
# Part 3:Training ANN

# compiling the output
ann.compile(optimizer = 'adam' ,loss = 'mean_squared_error')

# training ann on training dataset
ann.fit(X_train,y_train,batch_size = 32 , epochs =100)

Epoch 1/100
240/240 [==============================] - 0s 799us/step - loss: 58920.4414
Epoch 2/100
240/240 [==============================] - 0s 801us/step - loss: 409.2026
Epoch 3/100
240/240 [==============================] - 0s 823us/step - loss: 394.3663
Epoch 4/100
240/240 [==============================] - 0s 833us/step - loss: 376.0340
Epoch 5/100
240/240 [==============================] - 0s 794us/step - loss: 354.7352
Epoch 6/100
240/240 [==============================] - 0s 867us/step - loss: 331.1653
Epoch 7/100
240/240 [==============================] - 0s 775us/step - loss: 304.8435
Epoch 8/100
240/240 [==============================] - 0s 752us/step - loss: 277.9745
Epoch 9/100
240/240 [==============================] - 0s 824us/step - loss: 250.5782
Epoch 10/100
240/240 [==============================] - 0s 808us/step - loss: 222.3060
Epoch 11/100
240/240 [==============================] - 0s 790us/step - loss: 194.3427
Epoch 12/100
240/240 [============================

In [16]:
  # predicting test
  y_pred = ann.predict(X_test)
  np.printoptions(precision =2)
  print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[431.68218994 431.23      ]
 [462.72348022 460.01      ]
 [466.22311401 461.14      ]
 ...
 [473.45339966 473.26      ]
 [440.24359131 438.        ]
 [459.44772339 463.28      ]]
